### ISSUE TITLE
problem with residue-analysis

### ISSUE THREAD

**Issue by novakw** [rlabduke/MolProbity#1]
Compiled on linux 64 bit with no issues, but residue-analysis yields the following when running from the command line: 

sh: scrublines: command not found
Sorry: File format error:
mmCIF file must contain at least one data block

I am providing a pdb file and tried a couple with the same error

**Comment by novakw** [comment]
after running setup.sh (I thought was optional) this seems to work

**Comment by danielparton** [comment]
Thanks for reporting this - I encountered the same issue, and the solution also worked for me.
