### ISSUE TITLE
PHP issue PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by mandar5335** [rlabduke/MolProbity#18]
Hi,
I have installed molprobity on Ubuntu 20.04 LTS with php7.4. I need to use molprobity to get clashscore for RNA molecules. However, when I run molprobity/cmdline/clashscore command, I receive the following error:
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/mandar/softwares/molprobity/molprobity/lib/model.php on line 752

If this is a PHP version-related issue, which version is recommended? 

Thanks,
Mandar Kulkarni

**Comment by rlabduke** [comment]
Hi Mandar,

MolProbity has several incompatibilities with current PHP and requires a legacy version.  You can try the following to install a compatible PHP:

sudo apt install software-properties-commo
sudo add-apt-repository -y ppa:ondrej/php
sudo apt update
sudo apt list --upgradable
sudo su -
sudo aptitude install php5.6


Alternatively, you can skip the PHP layer and run the underlying clashscore code directly.
Run this command to set up the cctbx environment:
source path_to_MolProbity/build/setpaths.sh

Then run:
molprobity.clashscore filename.pdb

You may also find useful "molprobity.rna_validate filename.pdb"

Good luck,
-Christopher Williams
---Richardson Lab, Duke University

**Comment by mandar5335** [comment]
Hi Christopher,
Thanks for your reply and suggestions, I skipped the PHP layer and the molprobity.clashscore worked perfectly fine.

Best,
Mandar Kulkarni
